# Generated by Django 5.1.5 on 2025-01-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='Created_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(default='This is Description'),
        ),
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
